#pragma once

// Generated by the BetterVR bot's /credits command, do not edit by hand.
// Add, rename or hide people through supporters_overrides.json instead.

#include <array>
#include <cstddef>
#include <cstdint>

namespace Supporters {
    enum class Platform : uint8_t {
        GITHUB,
        PATREON,
        OTHER
    };

    enum class Tier : uint8_t {
        HIGH,
        STANDARD
    };

    struct Supporter {
        const char* name;
        Platform platform;
        Tier tier;
    };

    inline constexpr const char* LastUpdated = "2026-08-23";

    inline constexpr std::size_t HighTierCount = 7;

    inline constexpr std::array<Supporter, 30> List = {{
        { "GohTea", Platform::GITHUB, Tier::HIGH },
        { "Alex Paton", Platform::GITHUB, Tier::HIGH },
        { "Braxus", Platform::PATREON, Tier::HIGH },
        { "Dash Schlotterbeck", Platform::GITHUB, Tier::HIGH },
        { "Roy Takashi", Platform::PATREON, Tier::HIGH },
        { "Saeed Al-Ali", Platform::PATREON, Tier::HIGH },
        { "TheGhostOfSmittyWerbenjagerma...", Platform::GITHUB, Tier::HIGH },
        { "atari64", Platform::PATREON, Tier::STANDARD },
        { "BigBossSaladin", Platform::PATREON, Tier::STANDARD },
        { "JshodanVR", Platform::PATREON, Tier::STANDARD },
        { "Lortal", Platform::PATREON, Tier::STANDARD },
        { "Quinn's Modded Stuff", Platform::PATREON, Tier::STANDARD },
        { "Rick Mathot", Platform::PATREON, Tier::STANDARD },
        { "Slimmoo", Platform::PATREON, Tier::STANDARD },
        { "Team Cemu", Platform::PATREON, Tier::STANDARD },
        { "theLemonadeHeadStand", Platform::PATREON, Tier::STANDARD },
        { "Zach Rak", Platform::PATREON, Tier::STANDARD },
        { "Zerovolt0V", Platform::PATREON, Tier::STANDARD },
        { "beepsandblips", Platform::GITHUB, Tier::STANDARD },
        { "Carlos4321", Platform::GITHUB, Tier::STANDARD },
        { "darkmoldavite", Platform::GITHUB, Tier::STANDARD },
        { "giodude12", Platform::GITHUB, Tier::STANDARD },
        { "Memesy", Platform::GITHUB, Tier::STANDARD },
        { "Nikita Fajitaa", Platform::GITHUB, Tier::STANDARD },
        { "Tim Dawson", Platform::GITHUB, Tier::STANDARD },
        { "YeBoiDeLeau", Platform::GITHUB, Tier::STANDARD },
        { "Bearadactyle", Platform::PATREON, Tier::STANDARD },
        { "Empajadores", Platform::PATREON, Tier::STANDARD },
        { "peppered_eels", Platform::PATREON, Tier::STANDARD },
        { "everyling-max", Platform::GITHUB, Tier::STANDARD },
    }};
}
